source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Moya-SwiftyJSONMapper_Example' do
  pod 'Moya-SwiftyJSONMapper', :path => '../'
  pod 'Moya-SwiftyJSONMapper/RxSwift', :path => '../'
  pod 'Moya-SwiftyJSONMapper/ReactiveCocoa', :path => '../'
end

target 'Moya-SwiftyJSONMapper_Tests' do
  pod 'Moya-SwiftyJSONMapper', :path => '../'
  pod 'Moya-SwiftyJSONMapper/RxSwift', :path => '../'
  pod 'Moya-SwiftyJSONMapper/ReactiveCocoa', :path => '../'
  
end

# Build configurations
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
