source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

def shared_pods
    pod 'Moya-SwiftyJSONMapper', :path => '../'
    pod 'Moya-SwiftyJSONMapper/RxSwift', :path => '../'
    pod 'Moya-SwiftyJSONMapper/ReactiveCocoa', :path => '../'
end

target 'Moya-SwiftyJSONMapper_Example' do
    shared_pods
end

target 'Moya-SwiftyJSONMapper_Tests' do
    shared_pods
end

# Build configurations
post_install do |installer|
  swift4Targets = ['Moya', 'Moya-SwiftyJSONMapper']

  installer.pods_project.targets.each do |target|
      if swift4Targets.include? target.name
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      else
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.2'
        end
      end
  end
end
